version: 0.2

phases:
  build:
    commands:
      - zip -r code-test-$(date +"%Y%m%d%H%M%S").zip .
      - aws s3 cp code-test-$(date +"%Y%m%d%H%M%S").zip s3://hpsls-codedeploy/HPSLS/

artifacts:
  files: code-test-*.zip

