version: 0.2

phases:
  pre_build:
    commands:
      - export VERSION_COUNTER=$(($(aws s3 ls s3://bucket_name/folder_name/ | wc -l) + 1))

  build:
    commands:
      - zip -r hpslsa-v$VERSION_COUNTER.zip .
      - aws s3 cp hpslsa-v$VERSION_COUNTER.zip s3://hpsls-codedeploy/HPSLS/

artifacts:
  files: hpslsa-v$VERSION_COUNTER.zip
