#!/bin/bash

HPSLSA_DIR="/var/www/hpslsa"
HPSLSA_BACKUP_DIR="/var/www/hpslsa-old"

service php-fpm stop
service httpd stop


#############################################
# FOR SQS WORKER SUPERVISORD SERVICE STOP
##############################################
service supervisord stop

#if [ -f /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl ]; then
#    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a stop
#fi

#CodeDeploy complains in AutoScaling scenario as there is no file overwrite option, when codedeploy is launched automatically from ASG
#making a backup of the current nios system.

if [ -d $HPSLSA_BACKUP_DIR ]; then
    rm -rf $HPSLSA_BACKUP_DIR
fi

mv $HPSLSA_DIR $HPSLSA_BACKUP_DIR